//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH1217
{
	using System.Threading.Tasks;
	[TestFixture,Ignore("Not fixed yet")]
	public class FixtureAsync : BugTestCase
	{
		public override string BugNumber
		{
			get { return "NH1217"; }
		}

		protected override void OnTearDown()
		{
			using (ISession s = OpenSession())
			using (ITransaction tx = s.BeginTransaction())
			{
				s.Delete("from System.Object o");
				tx.Commit();
			}
		}

		/// <summary>
		/// +--------+          +--------+ 1   from   * +--------+
		///	|        | 1      * |        |--------------|        |
		///	|  Root  |----------|  Node  | 1    to    * |  Edge  |
		///	|        |          |        |--------------|        |
		///	+--------+          +--------+              +--------+ 
		/// </summary>
		[Test]
		public async Task NoExceptionMustBeThrownAsync()
		{
			using (ISession s = OpenSession())
			{
				using (ITransaction tx = s.BeginTransaction())
				{
					Root r = new Root();
					r.Name = "a root";

					INode n1 = r.AddNode("Node1");
					INode n2 = r.AddNode("Node2");

					IEdge e1 = new Edge();
					e1.Label = "Edge 1";
					e1.FromNode = n1;
					e1.ToNode = n2;
					
					n1.FromEdges.Add(e1);
					n2.ToEdges.Add(e1);
					
					await (s.SaveAsync(r));

					await (s.FlushAsync());
					await (tx.CommitAsync());
				}
			}
		}
	}
}