//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using System.Linq;
using NHibernate.Linq;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH3182
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture, Ignore("Not fixed yet.")]
	public class FixtureAsync : BugTestCase
	{
		protected override void OnSetUp()
		{
			var mother = new Lizard
				{
					BodyWeight = 48,
					Description = "Mother",
					Children = new List<Animal>()
				};
			var father = new Lizard
				{
					BodyWeight = 48,
					Description = "Father",
					Children = new List<Animal>()
				};
			var child = new Lizard
				{
					Mother = mother,
					Father = father,
					BodyWeight = 48,
					Description = "Child",
				};

			mother.Children.Add(child);
			father.Children.Add(child);

			using (var session = OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				session.Save(mother);
				session.Save(father);
				session.Save(child);

				transaction.Commit();
			}
		}

		protected override void OnTearDown()
		{
			using (var session = OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				session.Delete("from System.Object");

				transaction.Commit();
			}
		} 

		[Test]
		public async Task SelectManyPregnantStatusCast1Async()
		{
			using (var session = OpenSession())
			using (session.BeginTransaction())
			{
				var list = await ((session.Query<Animal>()
					.SelectMany(o => o.Children)
					.Where(o => o is Mammal)
					.Select(o => ((Mammal) o).Pregnant))
					.ToListAsync(CancellationToken.None));

				var count = list.Count();
				Assert.AreEqual(0, count);
			}
		}

		[Test]
		public async Task SelectManyPregnantStatusCast2Async()
		{
			using (var session = OpenSession())
			using (session.BeginTransaction())
			{
				var list = await ((session.Query<Animal>()
					.SelectMany(o => o.Children)
					.Where(o => o is Mammal)
					.Select(o => ((Mammal) o).Pregnant))
					.ToListAsync(CancellationToken.None));

				var count = list.Count();
				Assert.AreEqual(0, count);
			}
		}

		[Test]
		public async Task SelectManyPregnantStatusOfType1Async()
		{
			using (var session = OpenSession())
			using (session.BeginTransaction())
			{
				var list = await (session.Query<Animal>()
					.SelectMany(o => o.Children, (animal, animal1) => animal1)
					.OfType<Mammal>()
					.Select(o => o.Pregnant)
					.ToListAsync(CancellationToken.None));

				var count = list.Count();
				Assert.AreEqual(0, count);
			}
		}

		[Test]
		public async Task SelectManyPregnantStatusOfType2Async()
		{
			using (var session = OpenSession())
			using (session.BeginTransaction())
			{
				var list = await (session.Query<Animal>()
					.SelectMany(o => o.Children, (animal, animal1) => animal1)
					.OfType<Mammal>()
					.Select(o => o.Pregnant)
					.ToListAsync(CancellationToken.None));

				var count = list.Count();
				Assert.AreEqual(0, count);
			}
		}

		[Test]
		public async Task SelectPregnantStatusCastAsync()
		{
			using (var session = OpenSession())
			using (session.BeginTransaction())
			{
				var list = await ((session.Query<Animal>()
					.Where(o => o is Mammal)
					.Select(o => ((Mammal)o).Pregnant))
					.ToListAsync(CancellationToken.None));

				var count = list.Count();
				Assert.AreEqual(0, count);
			}
		}

		[Test]
		public async Task SelectPregnantStatusOfTypeAsync()
		{
			using (var session = OpenSession())
			using (session.BeginTransaction())
			{
				var list = await (session.Query<Animal>()
					.OfType<Mammal>()
					.Select(o => o.Pregnant)
					.ToListAsync(CancellationToken.None));

				var count = list.Count();
				Assert.AreEqual(0, count);
			}
		}

		[Test]
		public async Task SelectPregnantStatusAsync()
		{
			using (var session = OpenSession())
			using (session.BeginTransaction())
			{
				var list = await (session.Query<Mammal>()
					.Select(o => o.Pregnant)
					.ToListAsync(CancellationToken.None));

				var count = list.Count();
				Assert.AreEqual(0, count);
			}
		}
	}
}
