//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH2245
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		[Test]
		public async Task TestDelete_OptimisticLockNoneAsync()
		{
			Guid id;

			// persist a foo instance
			using (ISession session = OpenSession())
			{
				using (ITransaction tx = session.BeginTransaction())
				{
					var f = new Foo();
					f.Name = "Henry";
					f.Description = "description";
					await (session.SaveAsync(f, CancellationToken.None));
					await (tx.CommitAsync(CancellationToken.None));
					id = f.Id;
				}
			}

			using (ISession session1 = OpenSession())
			using (ISession session2 = OpenSession())
			{
				// Load the foo from two different sessions. Modify the foo in one session to bump the version in the database, and save. 
				// Then try to delete the foo from the other session. With optimistic lock set to none, this should succeed when the 2245
				// patch is applied to AbstractEntityPersister.cs. Without the patch, NH adds the version to the where clause of the delete
				// statement, and the delete fails.
				var f1 = await (session1.GetAsync<Foo>(id, CancellationToken.None));
				var f2 = await (session2.GetAsync<Foo>(id, CancellationToken.None));

				// Bump version
				using (ITransaction trans1 = session1.BeginTransaction())
				{
					f1.Description = "modified description";
					await (session1.UpdateAsync(f1, CancellationToken.None));
					await (trans1.CommitAsync(CancellationToken.None));
				}

				// Now delete from second session
				using (ITransaction trans2 = session2.BeginTransaction())
				{
					Assert.That(() => session2.Delete(f2), Throws.Nothing);
					await (trans2.CommitAsync(CancellationToken.None));
				}
			}

			// Assert that row is really gone
			using (ISession assertSession = OpenSession())
			{
				Assert.IsNull(await (assertSession.GetAsync<Foo>(id, CancellationToken.None)));
			}
		}
	}
}