//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NHibernate.Type;
using NUnit.Framework;

namespace NHibernate.Test.TypesTest
{
	using System.Threading.Tasks;
	using System.Threading;
	/// <summary>
	/// The Unit Tests for the ByteType.
	/// </summary>
	[TestFixture]
	public class ByteTypeFixtureAsync : TypeFixtureBase
	{
		protected override string TypeName
		{
			get { return "Byte"; }
		}

		[Test]
		public async Task ReadWriteAsync()
		{
			ByteClass basic = new ByteClass();
			basic.Id = 1;
			basic.ByteValue = (byte) 43;

			ISession s = OpenSession();
			await (s.SaveAsync(basic, CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			s.Close();

			s = OpenSession();
			basic = (ByteClass) await (s.LoadAsync(typeof(ByteClass), 1, CancellationToken.None));

			Assert.AreEqual((byte) 43, basic.ByteValue);

			await (s.DeleteAsync(basic, CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			s.Close();
		}
	}
}