//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NHibernate.Id.Enhanced
{
	using System.Threading.Tasks;
	/// <summary>
	/// Performs optimization on an optimizable identifier generator.  Typically
	/// this optimization takes the form of trying to ensure we do not have to
	/// hit the database on each and every request to get an identifier value.
	/// </summary>
	/// <remarks>
	/// <para>
	/// Optimizers work on constructor injection.  They should provide
	/// a constructor with the following arguments.
	/// </para>
	/// - <see cref="System.Type"/> The return type for the generated values.
	/// - <langword>int</langword> The increment size.
	/// </remarks>
	public partial interface IOptimizer
	{

		/// <summary>
		/// Generate an identifier value accounting for this specific optimization. 
		/// </summary>
		/// <param name="callback">Callback to access the underlying value source. </param>
		/// <returns>The generated identifier value.</returns>
		Task<object> GenerateAsync(IAccessCallback callback);
	}
}