//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;

using NUnit.Framework;
using NHibernate.Criterion;

namespace NHibernate.Test.NHSpecificTest.NH1018
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class NH1018FixtureAsync : BugTestCase
	{
		[Test]
		public async Task TestAsync()
		{
			using (ISession session = OpenSession())
			using (ITransaction tx = session.BeginTransaction())
			{
				Employer emr1 = new Employer("Test Employer 1");
				Employer emr2 = new Employer("Test Employer 2");

				Employee[] employees = new Employee[5];

				for (int i = 0; i < employees.Length; i++)
				{
					employees[i] = new Employee("Test Employee " + (i + 1).ToString());
				}

				emr1.AddEmployee(employees[0]);
				emr1.AddEmployee(employees[1]);
				emr1.AddEmployee(employees[2]);
				emr2.AddEmployee(employees[3]);
				emr2.AddEmployee(employees[4]);

				await (session.SaveAsync(emr1, CancellationToken.None));
				await (session.SaveAsync(emr2, CancellationToken.None));

				foreach (Employee emp in employees)
				{
					await (session.SaveAsync(emp, CancellationToken.None));
				}

				await (tx.CommitAsync(CancellationToken.None));
			}

			using (ISession session = OpenSession())
			{
				IList employers = await (session.CreateQuery("select emr from Employer emr inner join fetch emr.Employees")
					.SetResultTransformer(CriteriaSpecification.DistinctRootEntity)
					.ListAsync(CancellationToken.None));
				Assert.AreEqual(2, employers.Count);
			}

			using (ISession session = OpenSession())
			using (ITransaction tx = session.BeginTransaction())
			{
				await (session.DeleteAsync("from Employee", CancellationToken.None));
				await (session.DeleteAsync("from Employer", CancellationToken.None));
				await (tx.CommitAsync(CancellationToken.None));
			}
		}
	}
}