//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NHibernate.Dialect;
using NUnit.Framework;

namespace NHibernate.Test.SqlTest.Custom.Oracle
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class OracleCustomSQLFixtureAsync : CustomStoredProcSupportTest
	{
		protected override IList Mappings
		{
			get { return new[] { "SqlTest.Custom.Oracle.Mappings.hbm.xml", "SqlTest.Custom.Oracle.StoredProcedures.hbm.xml" }; }
		}

		protected override bool AppliesTo(NHibernate.Engine.ISessionFactoryImplementor factory)
		{
			return factory.ConnectionProvider.Driver is Driver.OracleDataClientDriver;
		}

		protected override bool AppliesTo(Dialect.Dialect dialect)
		{
			return dialect is Oracle8iDialect;
		}

		[Test]
		public async Task RefCursorOutStoredProcedureAsync()
		{
			ISession s = OpenSession();
			ITransaction t = s.BeginTransaction();

			Organization ifa = new Organization("IFA");
			Organization jboss = new Organization("JBoss");
			Person gavin = new Person("Gavin");
			Person kevin = new Person("Kevin");
			Employment emp = new Employment(gavin, jboss, "AU");
			Employment emp2 = new Employment(kevin, ifa, "EU");
			await (s.SaveAsync(ifa, CancellationToken.None));
			await (s.SaveAsync(jboss, CancellationToken.None));
			await (s.SaveAsync(gavin, CancellationToken.None));
			await (s.SaveAsync(kevin, CancellationToken.None));
			await (s.SaveAsync(emp, CancellationToken.None));
			await (s.SaveAsync(emp2, CancellationToken.None));

			IQuery namedQuery = s.GetNamedQuery("selectEmploymentsForRegion");
			namedQuery.SetString("regionCode", "EU");
			IList list = await (namedQuery.ListAsync(CancellationToken.None));
			Assert.That(list.Count, Is.EqualTo(1));
			await (s.DeleteAsync(emp2, CancellationToken.None));
			await (s.DeleteAsync(emp, CancellationToken.None));
			await (s.DeleteAsync(ifa, CancellationToken.None));
			await (s.DeleteAsync(jboss, CancellationToken.None));
			await (s.DeleteAsync(kevin, CancellationToken.None));
			await (s.DeleteAsync(gavin, CancellationToken.None));

			await (t.CommitAsync(CancellationToken.None));
			s.Close();
		}

	}
}