//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Linq.Expressions;

using NHibernate.Criterion.Lambda;
using NHibernate.Engine;
using NHibernate.Impl;
using NHibernate.SqlCommand;
using NHibernate.Transform;

namespace NHibernate.Criterion
{
	using System.Threading.Tasks;
	public abstract partial class QueryOver<TRoot> : QueryOver, IQueryOver<TRoot>
	{

		private async Task<IList<TRoot>> ListAsync()
		{
			return await (criteria.ListAsync<TRoot>()).ConfigureAwait(false);
		}

		private async Task<IList<U>> ListAsync<U>()
		{
			return await (criteria.ListAsync<U>()).ConfigureAwait(false);
		}

		private async Task<TRoot> SingleOrDefaultAsync()
		{
			return await (criteria.UniqueResultAsync<TRoot>()).ConfigureAwait(false);
		}

		private async Task<U> SingleOrDefaultAsync<U>()
		{
			return await (criteria.UniqueResultAsync<U>()).ConfigureAwait(false);
		}


		Task<IList<TRoot>> IQueryOver<TRoot>.ListAsync()
		{ return ListAsync(); }
async 
		Task<IList<U>> IQueryOver<TRoot>.ListAsync<U>()
		{ return await (ListAsync<U>()).ConfigureAwait(false); }
async 
		Task<int> IQueryOver<TRoot>.RowCountAsync()
		{ return await (ToRowCountQuery().SingleOrDefaultAsync<int>()).ConfigureAwait(false); }
async 
		Task<long> IQueryOver<TRoot>.RowCountInt64Async()
		{ return await (ToRowCountInt64Query().SingleOrDefaultAsync<long>()).ConfigureAwait(false); }

		Task<TRoot> IQueryOver<TRoot>.SingleOrDefaultAsync()
		{ return SingleOrDefaultAsync(); }
async 
		Task<U> IQueryOver<TRoot>.SingleOrDefaultAsync<U>()
		{ return await (SingleOrDefaultAsync<U>()).ConfigureAwait(false); }

	}

}
