//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Engine;

namespace NHibernate.Action
{
	using System.Threading.Tasks;
	
	/// <content>
	/// Contains generated async methods
	/// </content>
	public partial interface IExecutable
	{

		/// <summary> Execute this action</summary>
		Task ExecuteAsync();
	}
}
