//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Data.Common;
using NHibernate.Connection;

namespace NHibernate.Tool.hbm2ddl
{
	using System.Threading.Tasks;

	/// <summary>
	/// A <seealso cref="IConnectionHelper"/> implementation based on a provided
	/// <seealso cref="IConnectionProvider"/>.  Essentially, ensures that the connection
	/// gets cleaned up, but that the provider itself remains usable since it
	/// was externally provided to us.
	/// </summary>
	public partial class SuppliedConnectionProviderConnectionHelper : IConnectionHelper
	{

		public async Task PrepareAsync()
		{
			connection = await (provider.GetConnectionAsync()).ConfigureAwait(false);
		}
	}
}
