//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NHibernate.Persister.Entity;

namespace NHibernate.Event.Default
{
	using System.Threading.Tasks;
	public partial class DefaultPreLoadEventListener : IPreLoadEventListener
	{
		public virtual Task OnPreLoadAsync(PreLoadEvent @event)
		{
			IEntityPersister persister = @event.Persister;
			@event.Session.Interceptor.OnLoad(@event.Entity, @event.Id, @event.State, persister.PropertyNames, persister.PropertyTypes);
			return Task.CompletedTask;
		}
	}
}
