//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NHibernate.Persister.Entity;

namespace NHibernate.Event.Default
{
	using System.Threading.Tasks;
	/// <content>
	/// Contains generated async methods
	/// </content>
	public partial class DefaultPreLoadEventListener : IPreLoadEventListener
	{
		public virtual Task OnPreLoadAsync(PreLoadEvent @event)
		{
			try
			{
				OnPreLoad(@event);
				return Task.CompletedTask;
			}
			catch (Exception ex)
			{
				return Task.FromException<object>(ex);
			}
		}
	}
}
