//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;

namespace NHibernate.Event
{
	using System.Threading.Tasks;
	/// <summary>
	/// Defines the contract for handling of refresh events generated from a session.
	/// </summary>
	public partial interface IRefreshEventListener
	{
		/// <summary> Handle the given refresh event. </summary>
		/// <param name="event">The refresh event to be handled.</param>
		Task OnRefreshAsync(RefreshEvent @event);

		/// <summary>
		/// 
		/// </summary>
		/// <param name="event"></param>
		/// <param name="refreshedAlready"></param>
		Task OnRefreshAsync(RefreshEvent @event, IDictionary refreshedAlready);
	}
}