//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH3145
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		[Test]
		public async Task QueryWithLazyBaseClassShouldNotThrowNoPersisterForErrorAsync()
		{
			try
			{
				using (var s = OpenSession())
				using (var t = s.BeginTransaction())
				{
					var item1 = new Derived
					{
						LongContent = "LongLongLongLongLong"
					};
					var root = new Root
					{
						Base = item1
					};
					await (s.SaveAsync(item1, CancellationToken.None));
					await (s.SaveAsync(root, CancellationToken.None));
					await (t.CommitAsync(CancellationToken.None));
				}

				// This will succeed if either:
				// a) we do not initialize root.Base
				// or
				// b) Base.LongContent is made non-lazy (remove lazy properties)

				using (var s = OpenSession())
				using (var t = s.BeginTransaction())
				{
					var root = await (s.CreateQuery("from Root").UniqueResultAsync<Root>(CancellationToken.None));
					await (NHibernateUtil.InitializeAsync(root.Base, CancellationToken.None));
					var q = s.CreateQuery("from Derived d where d = ?")
						.SetEntity(0, root.Base);
					await (q.ListAsync(CancellationToken.None));
				}
			}
			finally
			{
				using (var s = OpenSession())
				using (var t = s.BeginTransaction())
				{
					await (s.DeleteAsync("from Root", CancellationToken.None));
					await (s.DeleteAsync("from Derived", CancellationToken.None));
					await (t.CommitAsync(CancellationToken.None));
				}
			}
		}
	}
}
