//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NHibernate.Criterion;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH276
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : TestCase
	{
		protected override string MappingsAssembly
		{
			get { return "NHibernate.Test"; }
		}

		protected override IList Mappings
		{
			get { return new string[] {"NHSpecificTest.NH276.Mappings.hbm.xml"}; }
		}

		/// <summary>
		/// Testing that the syntax of "manytoone.Id" works inside
		/// of an ICriteria.  This was broken in the upgrade to 0.8
		/// </summary>
		[Test]
		public async Task ManyToOneIdAsync()
		{
			Building madison = new Building();
			madison.Id = 1;
			madison.Number = "4800";

			Building college = new Building();
			college.Id = 2;
			college.Number = "6363";

			Office acctg = new Office();
			acctg.Id = 3;
			acctg.Worker = "Bean Counter";
			acctg.Location = college;

			Office hr = new Office();
			hr.Id = 4;
			hr.Worker = "benefits";
			hr.Location = madison;

			Office it = new Office();
			hr.Id = 5;
			it.Worker = "servers";
			it.Location = madison;

			ISession s = OpenSession();
			await (s.SaveAsync(madison, CancellationToken.None));
			await (s.SaveAsync(college, CancellationToken.None));
			await (s.SaveAsync(acctg, CancellationToken.None));
			await (s.SaveAsync(hr, CancellationToken.None));
			await (s.SaveAsync(it, CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			s.Close();

			s = OpenSession();

			ICriteria c = s.CreateCriteria(typeof(Office));
			c.Add(Expression.Eq("Location.Id", madison.Id));
			IList results = await (c.ListAsync(CancellationToken.None));

			Assert.AreEqual(2, results.Count, "2 objects");
			foreach (Office office in results)
			{
				Assert.AreEqual(madison.Id, office.Location.Id, "same location as criteria specified");
			}

			c = s.CreateCriteria(typeof(Office));
			c.Add(Expression.Eq("Location.Id", college.Id));
			results = await (c.ListAsync(CancellationToken.None));

			Assert.AreEqual(1, results.Count, "1 objects");
			foreach (Office office in results)
			{
				Assert.AreEqual(college.Id, office.Location.Id, "same location as criteria specified");
			}

			await (s.DeleteAsync("from Office ", CancellationToken.None));
			await (s.DeleteAsync("from Building", CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			s.Close();
		}
	}
}