//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NHibernate.Test.NHSpecificTest.LoadingNullEntityInSet
{
	using System.Collections;
	using Mapping;
	using NUnit.Framework;
	using SqlCommand;
	using Type;
	using TestCase=NHibernate.Test.TestCase;
	using System.Threading.Tasks;
	using System.Threading;

	[TestFixture]
    public class FixtureAsync : TestCase
    {

        protected override IList Mappings
        {
            get { return new string[] { "NHSpecificTest.LoadingNullEntityInSet.Mappings.hbm.xml" }; }
        }

        protected override string MappingsAssembly
        {
            get { return "NHibernate.Test"; }
        }

		protected override void BuildSessionFactory()
		{
			cfg.GetCollectionMapping(typeof (Employee).FullName + ".Primaries")
				.CollectionTable.Name = "WantedProfessions";
			cfg.GetCollectionMapping(typeof (Employee).FullName + ".Secondaries")
				.CollectionTable.Name = "WantedProfessions";
			base.BuildSessionFactory();
		}

		protected override void OnTearDown()
		{
			cfg.GetCollectionMapping(typeof (Employee).FullName + ".Primaries")
				.CollectionTable.Name = "WantedProfessions_DUMMY_1";
			cfg.GetCollectionMapping(typeof (Employee).FullName + ".Secondaries")
				.CollectionTable.Name = "WantedProfessions_DUMMY_2";
			base.OnTearDown();
		}

        [Test]
        public async Task CanHandleNullEntityInListAsync()
        {
            using (ISession sess = OpenSession())
            using (ITransaction tx = sess.BeginTransaction())
            {
                Employee e = new Employee();
                PrimaryProfession ppc = new PrimaryProfession();
				await (sess.SaveAsync(e, CancellationToken.None));
            	await (sess.SaveAsync(ppc, CancellationToken.None));
            	await (sess.FlushAsync(CancellationToken.None));

				WantedProfession wanted = new WantedProfession();
            	wanted.Id = 15;
				wanted.Employee = e;
				wanted.PrimaryProfession = ppc;

            	await (sess.SaveAsync(wanted, CancellationToken.None));

				await (tx.CommitAsync(CancellationToken.None));
            }

            using (ISession sess = OpenSession())
            {
            	ICriteria criteria = sess.CreateCriteria(typeof(Employee));
            	criteria.CreateCriteria("Primaries", JoinType.LeftOuterJoin);
				criteria.CreateCriteria("Secondaries", JoinType.LeftOuterJoin);
            	await (criteria.ListAsync(CancellationToken.None));
            }


        	using (ISession sess = OpenSession())
            {
				await (sess.DeleteAsync("from WantedProfession", CancellationToken.None));
				await (sess.FlushAsync(CancellationToken.None));
				await (sess.DeleteAsync("from PrimaryProfession", CancellationToken.None));
                await (sess.FlushAsync(CancellationToken.None));
				await (sess.DeleteAsync("from Employee", CancellationToken.None));
                await (sess.FlushAsync(CancellationToken.None));
            }
        }
    }
}
