//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH525
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		public override string BugNumber
		{
			get { return "NH525"; }
		}

		[Test]
		public async Task DoSomethingAsync()
		{
			NonAbstract obj = new NonAbstract();

			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				await (s.SaveAsync(obj, CancellationToken.None));
				await (t.CommitAsync(CancellationToken.None));
			}

			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				AbstractBase baseObj = (AbstractBase) await (s.LoadAsync(typeof(AbstractBase), obj.Id, CancellationToken.None));
				Assert.AreEqual(NonAbstract.AbstractMethodResult, baseObj.AbstractMethod());
				await (s.DeleteAsync(baseObj, CancellationToken.None));
				await (t.CommitAsync(CancellationToken.None));
			}
		}
	}
}