//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NHibernate.Engine;

namespace NHibernate.Type
{
	using System.Threading.Tasks;
	/// <content>
	/// Contains generated async methods
	/// </content>
	public partial interface IVersionType : IType
	{
		/// <summary>
		/// When implemented by a class, increments the version.
		/// </summary>
		/// <param name="current">The current version</param>
		/// <param name="session">The current session, if available.</param>
		/// <returns>an instance of the <see cref="IType"/> that has been incremented.</returns>
		Task<object> NextAsync(object current, ISessionImplementor session);

		/// <summary>
		/// When implemented by a class, gets an initial version.
		/// </summary>
		/// <param name="session">The current session, if available.</param>
		/// <returns>An instance of the type.</returns>
		Task<object> SeedAsync(ISessionImplementor session);
	}
}
