//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH2374
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class NH2374FixtureAsync : BugTestCase
	{
		[Test]
		public async Task OneToOne_with_EntityMode_MapAsync()
		{
			int id;

			using (ISession sroot = OpenSession())
			{
				using (ISession s = sroot.GetChildSession())
				{
					using (ITransaction t = s.BeginTransaction())
					{
						var parent = new Hashtable();
						var child = new Hashtable
						            	{
						            		{"Parent", parent}
						            	};

						parent["Child"] = child;

						id = (int) await (s.SaveAsync("Parent", parent, CancellationToken.None));
						await (s.FlushAsync(CancellationToken.None));

						await (t.CommitAsync(CancellationToken.None));
					}
				}
			}

			using (ISession s = OpenSession())
			{
				using (ITransaction t = s.BeginTransaction())
				{
					var p = await (s.GetAsync("Parent", id, CancellationToken.None)) as IDictionary;

					Assert.That(p["Child"], Is.Not.Null);

					await (s.DeleteAsync("Parent", p, CancellationToken.None));

					await (t.CommitAsync(CancellationToken.None));
				}
			}
		}

		[Test]
		public async Task OneToOne_with_EntityMode_PocoAsync()
		{
			int id;

			using (ISession s = OpenSession())
			{
				using (ITransaction t = s.BeginTransaction())
				{
					var parent = new Hashtable();
					var child = new Hashtable
					            	{
					            		{"Parent", parent}
					            	};

					parent["Child"] = child;

					id = (int) await (s.SaveAsync("Parent", parent, CancellationToken.None));
					await (s.FlushAsync(CancellationToken.None));

					await (t.CommitAsync(CancellationToken.None));
				}
			}

			using (ISession s = OpenSession())
			{
				using (ITransaction t = s.BeginTransaction())
				{
					var p = await (s.GetAsync("Parent", id, CancellationToken.None)) as IDictionary;

					Assert.That(p["Child"], Is.Not.Null);

					await (s.DeleteAsync("Parent", p, CancellationToken.None));

					await (t.CommitAsync(CancellationToken.None));
				}
			}
		}
	}
}