//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Dialect;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH1654
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		public override string BugNumber
		{
			get { return "NH1654"; }
		}

		protected override bool AppliesTo(NHibernate.Dialect.Dialect dialect)
		{
			return dialect is MsSql2000Dialect;
		}

		[Test]
		public async Task TestAsync()
		{
			int employeeId;
			using (ISession sess = OpenSession())
			using (ITransaction tx = sess.BeginTransaction())
			{
				var emp = new Employee();
				emp.Id = 1;
				emp.FirstName = "John";

				await (sess.SaveAsync(emp, CancellationToken.None));

				await (tx.CommitAsync(CancellationToken.None));

				employeeId = emp.Id;
			}

			using (ISession sess = OpenSession())
			using (ITransaction tx = sess.BeginTransaction())
			{
				var load = await (sess.LoadAsync<Employee>(employeeId, CancellationToken.None));
				Assert.AreEqual("John", load.FirstNameFormula);

				await (tx.CommitAsync(CancellationToken.None));
			}

			using (ISession sess = OpenSession())
			using (ITransaction tx = sess.BeginTransaction())
			{
				await (sess.DeleteAsync("from Employee", CancellationToken.None));
				await (tx.CommitAsync(CancellationToken.None));
			}
		}
	}
}