//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Cfg;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH1978
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class AliasTestAsync : BugTestCase
	{
		[Test]
		public async Task ShouldReturnPlanFromEmployeeAsync()
		{
			using(var s = OpenSession())
			using (var trans = s.BeginTransaction())
			{
				var plan = new _401k {PlanName = "test"};
				await (s.SaveAsync(plan, CancellationToken.None));
				await (s.FlushAsync(CancellationToken.None));
				await (s.RefreshAsync(plan, CancellationToken.None));
				var emp = new Employee {EmpName = "name", PlanParent = plan};
				await (s.SaveAsync(emp, CancellationToken.None));

				trans.Rollback();
			}
		}
	}
}