//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Collections.Generic;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH2907
{
	using System.Threading.Tasks;
	using System.Threading;
	/// <summary>
	/// Similar to NH-2113 but with dynamic entity
	/// </summary>
	[TestFixture, Ignore("Not fixed yet.")]
	public class FixtureAsync : BugTestCase
	{
		[Test]
		public async Task ShouldNotEagerLoadKeyManyToOneWhenOverridingGetHashCodeAsync()
		{
			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				var grp = new Group();
				await (s.SaveAsync(grp, CancellationToken.None));

				var loanId = new Dictionary<string, object>
								{
									{"Id", 1},
									{"Group", grp}
								};
				var loan = new Dictionary<string, object>
								{
									{"CompId", loanId}, 
									{"Name", "money!!!"}
								};
				await (s.SaveAsync("Loan", loan, CancellationToken.None));

				await (tx.CommitAsync(CancellationToken.None));
			}

			bool isInitialized;
			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				var loan = await (s.CreateQuery("select l from Loan l")
					 .UniqueResultAsync<IDictionary>(CancellationToken.None));

				var compId = (IDictionary)loan["CompId"];
				var group = compId["Group"];

				Assert.That(@group, Is.Not.Null);

				isInitialized = NHibernateUtil.IsInitialized(group);

				await (tx.CommitAsync(CancellationToken.None));
			}
			Assert.That(isInitialized, Is.False);
		}

		protected override void OnTearDown()
		{
			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				s.Delete("from System.Object");
				tx.Commit();
			}
		}
	}
}
