//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH318
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : TestCase
	{
		protected override string MappingsAssembly
		{
			get { return "NHibernate.Test"; }
		}

		protected override IList Mappings
		{
			get { return new string[] {"NHSpecificTest.NH318.Mappings.hbm.xml"}; }
		}

		[Test]
		public async Task DeleteWithNotNullPropertySetToNullAsync()
		{
			ISession session = OpenSession();
			NotNullPropertyHolder a = new NotNullPropertyHolder();
			a.NotNullProperty = "Value";
			await (session.SaveAsync(a, CancellationToken.None));
			await (session.FlushAsync(CancellationToken.None));
			a.NotNullProperty = null;
			await (session.DeleteAsync(a, CancellationToken.None));
			await (session.FlushAsync(CancellationToken.None));
			session.Close();
		}
	}
}