//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Collections.Generic;
using System.Linq;
using NHibernate.Cfg;
using NHibernate.Dialect;
using NHibernate.Criterion;
using NHibernate.Proxy;
using NHibernate.SqlCommand;
using NHibernate.Transform;
using NHibernate.Type;
using NHibernate.Util;
using NUnit.Framework;

namespace NHibernate.Test.ReadOnly
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class ReadOnlyCriteriaQueryTestAsync : AbstractReadOnlyTest
	{
		protected override string MappingsAssembly
		{
			get { return "NHibernate.Test"; }
		}

		protected override IList Mappings
		{
			get { return new string[] { "ReadOnly.Enrolment.hbm.xml" }; }
		}
		
		protected override void Configure(Configuration configuration)
		{
			base.Configure(configuration);
			configuration.SetProperty(Environment.UseQueryCache, "true");
			configuration.SetProperty(Environment.CacheRegionPrefix, "criteriaquerytest");
			configuration.SetProperty(Environment.UseSecondLevelCache, "true");
		}

		[Test]
		public async Task ModifiableSessionDefaultCriteriaAsync()
		{
			Sfi.Statistics.Clear();
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				Course coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			Assert.That(sessions.Statistics.EntityInsertCount, Is.EqualTo(4));
			Assert.That(sessions.Statistics.EntityUpdateCount, Is.EqualTo(0));

			sessions.Statistics.Clear();
				
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				ICriteria criteria = s.CreateCriteria<Student>();
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.False);
				Assert.That(criteria.IsReadOnly, Is.False);
				
				Student gavin = (Student)await (criteria.UniqueResultAsync(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.False);
				Assert.That(criteria.IsReadOnly, Is.False);
				Assert.That(s.IsReadOnly(gavin), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}

			Assert.That(sessions.Statistics.EntityUpdateCount, Is.EqualTo(1));
			Assert.That(sessions.Statistics.EntityDeleteCount, Is.EqualTo(4));
			
			sessions.Statistics.Clear();
		}
		
		[Test]
		public async Task ModifiableSessionReadOnlyCriteriaAsync()
		{
			await (DefaultTestSetupAsync(CancellationToken.None));

			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				ICriteria criteria = s.CreateCriteria<Student>().SetReadOnly(true);
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ModifiableSessionModifiableCriteriaAsync()
		{
			await (DefaultTestSetupAsync(CancellationToken.None));

			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				ICriteria criteria = s.CreateCriteria<Student>();
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.False);
				Assert.That(criteria.IsReadOnly, Is.False);
				
				criteria.SetReadOnly(false);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				Assert.That(s.IsReadOnly(gavin), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ReadOnlySessionDefaultCriteriaAsync()
		{
			await (DefaultTestSetupAsync(CancellationToken.None));

			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				s.DefaultReadOnly = true;
				
				ICriteria criteria = s.CreateCriteria<Student>();
				Assert.That(s.DefaultReadOnly, Is.True);
				Assert.That(criteria.IsReadOnlyInitialized, Is.False);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.True);
				Assert.That(criteria.IsReadOnlyInitialized, Is.False);
				Assert.That(criteria.IsReadOnly, Is.True);
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ReadOnlySessionReadOnlyCriteriaAsync()
		{
			await (DefaultTestSetupAsync(CancellationToken.None));
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				s.DefaultReadOnly = true;
				
				ICriteria criteria = s.CreateCriteria<Student>();
				Assert.That(s.DefaultReadOnly, Is.True);
				Assert.That(criteria.IsReadOnlyInitialized, Is.False);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				criteria.SetReadOnly(true);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.True);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}

		[Test]
		public async Task ReadOnlySessionModifiableCriteriaAsync()
		{
			await (DefaultTestSetupAsync(CancellationToken.None));
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				s.DefaultReadOnly = true;
				
				ICriteria criteria = s.CreateCriteria<Student>();
				Assert.That(s.DefaultReadOnly, Is.True);
				Assert.That(criteria.IsReadOnlyInitialized, Is.False);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				criteria.SetReadOnly(false);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.True);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				Assert.That(s.IsReadOnly(gavin), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ReadOnlyCriteriaReturnsModifiableExistingEntityAsync()
		{
			Course coursePreferred = null;
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Assert.That(s.DefaultReadOnly, Is.False);
				
				coursePreferred = await (s.GetAsync<Course>(coursePreferred.CourseCode, CancellationToken.None));
				Assert.That(s.IsReadOnly(coursePreferred), Is.False);
				
				ICriteria criteria = s.CreateCriteria<Student>().SetReadOnly(true);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ReadOnlyCriteriaReturnsExistingModifiableProxyNotInitAsync()
		{
			Course coursePreferred = null;
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Assert.That(s.DefaultReadOnly, Is.False);
				
				coursePreferred = await (s.LoadAsync<Course>(coursePreferred.CourseCode, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.False);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				
				ICriteria criteria = s.CreateCriteria<Student>().SetReadOnly(true);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.False);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(coursePreferred, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ReadOnlyCriteriaReturnsExistingModifiableProxyInitAsync()
		{
			Course coursePreferred = null;
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Assert.That(s.DefaultReadOnly, Is.False);
				
				coursePreferred = await (s.LoadAsync<Course>(coursePreferred.CourseCode, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.False);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(coursePreferred, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				
				ICriteria criteria = s.CreateCriteria<Student>().SetReadOnly(true);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.True);
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.True);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(coursePreferred, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);

				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ModifiableCriteriaReturnsExistingReadOnlyEntityAsync()
		{
			Course coursePreferred = null;
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Assert.That(s.DefaultReadOnly, Is.False);
				
				coursePreferred = await (s.GetAsync<Course>(coursePreferred.CourseCode, CancellationToken.None));
				Assert.That(s.IsReadOnly(coursePreferred), Is.False);
				s.SetReadOnly(coursePreferred, true);
				
				ICriteria criteria = s.CreateCriteria<Student>().SetReadOnly(false);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				Assert.That(s.IsReadOnly(gavin), Is.False);
				Assert.That(s.IsReadOnly(coursePreferred), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);
				
				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ModifiableCriteriaReturnsExistingReadOnlyProxyNotInitAsync()
		{
			Course coursePreferred = null;
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Assert.That(s.DefaultReadOnly, Is.False);
				
				coursePreferred = await (s.LoadAsync<Course>(coursePreferred.CourseCode, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.False);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				s.SetReadOnly(coursePreferred, true);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, true, CancellationToken.None));
				
				ICriteria criteria = s.CreateCriteria<Student>().SetReadOnly(false);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				Assert.That(s.IsReadOnly(gavin), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.False);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, true, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(coursePreferred, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, coursePreferred, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);
				
				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task ModifiableCriteriaReturnsExistingReadOnlyProxyInitAsync()
		{
			Course coursePreferred = null;
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Assert.That(s.DefaultReadOnly, Is.False);
				
				coursePreferred = await (s.LoadAsync<Course>(coursePreferred.CourseCode, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.False);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(coursePreferred, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, coursePreferred, false, CancellationToken.None));
				s.SetReadOnly(coursePreferred, true);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, true, CancellationToken.None));
				
				ICriteria criteria = s.CreateCriteria<Student>().SetReadOnly(false);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				
				Student gavin = await (criteria.UniqueResultAsync<Student>(CancellationToken.None));
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(criteria.IsReadOnlyInitialized, Is.True);
				Assert.That(criteria.IsReadOnly, Is.False);
				Assert.That(s.IsReadOnly(gavin), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(coursePreferred), Is.True);
				await (CheckProxyReadOnlyAsync(s, coursePreferred, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);
				
				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				Enrolment enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));

				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(enrolment.Course, CancellationToken.None));
				await (s.DeleteAsync(enrolment, CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task SubselectAsync()
		{
			Student gavin = null;
			Enrolment enrolment = null;
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, CancellationToken.None));
		
				Course coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, CancellationToken.None));
		
				gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, CancellationToken.None));
		
				enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, CancellationToken.None));
		
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				DetachedCriteria dc = NHibernate.Criterion.DetachedCriteria.For<Student>()
					.Add(Property.ForName("StudentNumber").Eq(232L))
					.SetProjection(Property.ForName("Name"));
				
				gavin = await (s.CreateCriteria<Student>()
					.Add(Subqueries.Exists(dc))
					.SetReadOnly(true)
					.UniqueResultAsync<Student>(CancellationToken.None));
				
				Assert.That(s.DefaultReadOnly, Is.False);
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.False);
				
				await (NHibernateUtil.InitializeAsync(gavin.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, gavin.PreferredCourse, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.False);
				
				await (NHibernateUtil.InitializeAsync(gavin.Enrolments, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(gavin.Enrolments), Is.True);
				Assert.That(gavin.Enrolments.Count, Is.EqualTo(1));
				IEnumerator<Enrolment> enrolments = gavin.Enrolments.GetEnumerator();
				enrolments.MoveNext();
				enrolment = enrolments.Current;
				Assert.That(s.IsReadOnly(enrolment), Is.False);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, false, CancellationToken.None));
				
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				DetachedCriteria dc = NHibernate.Criterion.DetachedCriteria.For<Student>("st")
					.Add(Property.ForName("st.StudentNumber").EqProperty("e.StudentNumber"))
					.SetProjection(Property.ForName("Name"));
				
				enrolment = await (s.CreateCriteria<Enrolment>("e")
					.Add(Subqueries.Eq("Gavin King", dc))
					.SetReadOnly(true)
					.UniqueResultAsync<Enrolment>(CancellationToken.None));
				
				Assert.That(s.IsReadOnly(enrolment), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.True);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student, true, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(enrolment.Student, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student), Is.True);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student.PreferredCourse, false, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(enrolment.Student.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student.PreferredCourse, false, CancellationToken.None));
			
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				DetachedCriteria dc = NHibernate.Criterion.DetachedCriteria.For<Student>("st")
					.CreateCriteria("Enrolments")
					.CreateCriteria("Course")
					.Add(Property.ForName("Description").Eq("Hibernate Training"))
					.SetProjection(Property.ForName("st.Name"));
				
				enrolment = await (s.CreateCriteria<Enrolment>("e")
					.Add(Subqueries.Eq("Gavin King", dc))
					.SetReadOnly(true)
					.UniqueResultAsync<Enrolment>(CancellationToken.None));
				
				Assert.That(s.IsReadOnly(enrolment), Is.True);
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(enrolment.Course, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Course), Is.True);
				await (CheckProxyReadOnlyAsync(s, enrolment.Course, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student, true, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(enrolment.Student, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student), Is.True);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student, true, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student.PreferredCourse), Is.False);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student.PreferredCourse, false, CancellationToken.None));
				
				await (NHibernateUtil.InitializeAsync(enrolment.Student.PreferredCourse, CancellationToken.None));
				Assert.That(NHibernateUtil.IsInitialized(enrolment.Student.PreferredCourse), Is.True);
				await (CheckProxyReadOnlyAsync(s, enrolment.Student.PreferredCourse, false, CancellationToken.None));
			
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				await (s.DeleteAsync(gavin.PreferredCourse, CancellationToken.None));
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(gavin.Enrolments.First().Course, CancellationToken.None));
				await (s.DeleteAsync(gavin.Enrolments.First(), CancellationToken.None));

				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task DetachedCriteriaAsync()
		{
			DetachedCriteria dc = NHibernate.Criterion.DetachedCriteria.For<Student>()
				.Add(Property.ForName("Name").Eq("Gavin King"))
				.AddOrder(Order.Asc("StudentNumber"));
			
			byte[] bytes = SerializationHelper.Serialize(dc);
			
			dc = (DetachedCriteria)SerializationHelper.Deserialize(bytes);
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				
				Student bizarroGavin = new Student();
				bizarroGavin.Name = "Gavin King";
				bizarroGavin.StudentNumber = 666;
				
				await (s.PersistAsync(bizarroGavin, CancellationToken.None));
				await (s.PersistAsync(gavin, CancellationToken.None));
				
				await (t.CommitAsync(CancellationToken.None));
			}
			
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				IList result = await (dc.GetExecutableCriteria(s)
					.SetMaxResults(3)
					.SetReadOnly(true)
					.ListAsync(CancellationToken.None));
				
				Assert.That(result.Count, Is.EqualTo(2));
				
				Student gavin = (Student)result[0];
				Student bizarroGavin = (Student)result[1];
				
				Assert.That(gavin.StudentNumber, Is.EqualTo(232));
				Assert.That(bizarroGavin.StudentNumber, Is.EqualTo(666));
				
				Assert.That(s.IsReadOnly(gavin), Is.True);
				Assert.That(s.IsReadOnly(bizarroGavin), Is.True);
				
				await (s.DeleteAsync(gavin, CancellationToken.None));
				await (s.DeleteAsync(bizarroGavin, CancellationToken.None));
				
				await (t.CommitAsync(CancellationToken.None));
			}
		}
		
		[Test]
		public async Task TwoAliasesCacheAsync()
		{
			ISession s = OpenSession();
			ITransaction t = s.BeginTransaction();
			
			Course course = new Course();
			course.CourseCode = "HIB";
			course.Description = "Hibernate Training";
			await (s.SaveAsync(course, CancellationToken.None));
			
			Student gavin = new Student();
			gavin.Name = "Gavin King";
			gavin.StudentNumber  = 666;
			await (s.SaveAsync(gavin, CancellationToken.None));
			
			Student xam = new Student();
			xam.Name = "Max Rydahl Andersen";
			xam.StudentNumber  = 101;
			await (s.SaveAsync(xam, CancellationToken.None));
			
			Enrolment enrolment1 = new Enrolment();
			enrolment1.Course = course;
			enrolment1.CourseCode = course.CourseCode;
			enrolment1.Semester = 1;
			enrolment1.Year = 1999;
			enrolment1.Student = xam;
			enrolment1.StudentNumber = xam.StudentNumber;
			xam.Enrolments.Add(enrolment1);
			await (s.SaveAsync(enrolment1, CancellationToken.None));
			
			Enrolment enrolment2 = new Enrolment();
			enrolment2.Course = course;
			enrolment2.CourseCode = course.CourseCode;
			enrolment2.Semester = 3;
			enrolment2.Year = 1998;
			enrolment2.Student = gavin;
			enrolment2.StudentNumber = gavin.StudentNumber;
			gavin.Enrolments.Add(enrolment2);
			await (s.SaveAsync(enrolment2, CancellationToken.None));
			await (t.CommitAsync(CancellationToken.None));
			s.Close();

			s = OpenSession();
			t = s.BeginTransaction();
			
			IList list = await (s.CreateCriteria<Enrolment>()
				.CreateAlias("Student", "s")
				.CreateAlias("Course", "c")
				.Add(Restrictions.IsNotEmpty("s.Enrolments"))
				.SetCacheable(true)
				.SetReadOnly(true)
				.ListAsync(CancellationToken.None));
			
			Assert.That(list.Count, Is.EqualTo(2));

			Enrolment e = (Enrolment)list[0];
			if (e.Student.StudentNumber == xam.StudentNumber)
			{
				enrolment1 = e;
				enrolment2 = (Enrolment)list[1];
			}
			else if (e.Student.StudentNumber == gavin.StudentNumber)
			{
				enrolment2 = e;
				enrolment1 = (Enrolment)list[1];
			}
			else
			{
				Assert.Fail("Enrolment has unknown student number: " + e.Student.StudentNumber);
			}

			Assert.That(s.IsReadOnly(enrolment1), Is.True);
			Assert.That(s.IsReadOnly(enrolment2), Is.True);
			Assert.That(s.IsReadOnly(enrolment1.Course), Is.True);
			Assert.That(s.IsReadOnly(enrolment2.Course), Is.True);
			Assert.That(enrolment1.Course, Is.SameAs(enrolment2.Course));
			Assert.That(s.IsReadOnly(enrolment1.Student), Is.True);
			Assert.That(s.IsReadOnly(enrolment2.Student), Is.True);

			await (t.CommitAsync(CancellationToken.None));
			s.Close();
	
			s = OpenSession();
			t = s.BeginTransaction();
			
			list = await (s.CreateCriteria<Enrolment>()
				.CreateAlias("Student", "s")
				.CreateAlias("Course", "c")
				.SetReadOnly(true)
				.Add(Restrictions.IsNotEmpty("s.Enrolments"))
				.SetCacheable(true)
				.SetReadOnly(true)
				.ListAsync(CancellationToken.None));
		
			Assert.That(list.Count, Is.EqualTo(2));

			e = (Enrolment)list[0];
			if (e.Student.StudentNumber == xam.StudentNumber)
			{
				enrolment1 = e;
				enrolment2 = (Enrolment)list[1];
			}
			else if (e.Student.StudentNumber == gavin.StudentNumber) {
				enrolment2 = e;
				enrolment1 = (Enrolment)list[1];
			}
			else
			{
				Assert.Fail("Enrolment has unknown student number: " + e.Student.StudentNumber);
			}

			Assert.That(s.IsReadOnly(enrolment1), Is.True);
			Assert.That(s.IsReadOnly(enrolment2), Is.True);
			Assert.That(s.IsReadOnly(enrolment1.Course), Is.True);
			Assert.That(s.IsReadOnly(enrolment2.Course), Is.True);
			Assert.That(enrolment1.Course, Is.SameAs(enrolment2.Course));
			Assert.That(s.IsReadOnly(enrolment1.Student), Is.True);
			Assert.That(s.IsReadOnly(enrolment2.Student), Is.True);

			await (t.CommitAsync(CancellationToken.None));
			s.Close();
	
			s = OpenSession();
			t = s.BeginTransaction();
			
			list = await (s.CreateCriteria<Enrolment>()
				.SetReadOnly(true)
				.CreateAlias("Student", "s")
				.CreateAlias("Course", "c")
				.Add(Restrictions.IsNotEmpty("s.Enrolments"))
				.SetCacheable(true)
				.ListAsync(CancellationToken.None));
			
			Assert.That(list.Count, Is.EqualTo(2));

			e = (Enrolment)list[0];
			if (e.Student.StudentNumber == xam.StudentNumber)
			{
				enrolment1 = e;
				enrolment2 = (Enrolment)list[1];
			}
			else if (e.Student.StudentNumber == gavin.StudentNumber)
			{
				enrolment2 = e;
				enrolment1 = (Enrolment)list[1];
			}
			else
			{
				Assert.Fail("Enrolment has unknown student number: " + e.Student.StudentNumber);
			}

			Assert.That(s.IsReadOnly(enrolment1), Is.True);
			Assert.That(s.IsReadOnly(enrolment2), Is.True);
			Assert.That(s.IsReadOnly(enrolment1.Course), Is.True);
			Assert.That(s.IsReadOnly(enrolment2.Course), Is.True);
			Assert.That(enrolment1.Course, Is.SameAs(enrolment2.Course));
			Assert.That(s.IsReadOnly(enrolment1.Student), Is.True);
			Assert.That(s.IsReadOnly(enrolment2.Student), Is.True);

			await (s.DeleteAsync(enrolment1, CancellationToken.None));
			await (s.DeleteAsync(enrolment2, CancellationToken.None));
			await (s.DeleteAsync(enrolment1.Course, CancellationToken.None));
			await (s.DeleteAsync(enrolment1.Student, CancellationToken.None));
			await (s.DeleteAsync(enrolment2.Student, CancellationToken.None));
		
			await (t.CommitAsync(CancellationToken.None));
			s.Close();
		}
		
		private async Task DefaultTestSetupAsync(CancellationToken cancellationToken = default(CancellationToken))
		{
			using (ISession s = OpenSession())
			using (ITransaction t = s.BeginTransaction())
			{
				Course course = new Course();
				course.CourseCode = "HIB";
				course.Description = "Hibernate Training";
				await (s.PersistAsync(course, cancellationToken));
		
				Course coursePreferred = new Course();
				coursePreferred.CourseCode = "JBOSS";
				coursePreferred.Description = "JBoss";
				await (s.PersistAsync(coursePreferred, cancellationToken));
		
				Student gavin = new Student();
				gavin.Name = "Gavin King";
				gavin.StudentNumber = 232;
				gavin.PreferredCourse = coursePreferred;
				await (s.PersistAsync(gavin, cancellationToken));
		
				Enrolment enrolment = new Enrolment();
				enrolment.Course = course;
				enrolment.CourseCode = course.CourseCode;
				enrolment.Semester = 3;
				enrolment.Year = 1998;
				enrolment.Student = gavin;
				enrolment.StudentNumber = gavin.StudentNumber;
				gavin.Enrolments.Add(enrolment);
				await (s.PersistAsync(enrolment, cancellationToken));
		
				await (t.CommitAsync(cancellationToken));
			}
		}
		
		private async Task CheckProxyReadOnlyAsync(ISession s, object proxy, bool expectedReadOnly, CancellationToken cancellationToken = default(CancellationToken))
		{
			Assert.That(proxy, Is.InstanceOf<INHibernateProxy>());
			ILazyInitializer li = ((INHibernateProxy)proxy).HibernateLazyInitializer;
			Assert.That(s, Is.SameAs(li.Session));
			Assert.That(s.IsReadOnly(proxy), Is.EqualTo(expectedReadOnly));
			Assert.That(li.ReadOnly, Is.EqualTo(expectedReadOnly));
			Assert.That(NHibernateUtil.IsInitialized(proxy), Is.Not.EqualTo(li.IsUninitialized));
			if (NHibernateUtil.IsInitialized(proxy))
			{
				Assert.That(s.IsReadOnly(await (li.GetImplementationAsync(cancellationToken))), Is.EqualTo(expectedReadOnly));
			}
		}
	}
}
