//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NUnit.Framework;

namespace NHibernate.Test.ListIndex
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class SimpleOneToManyTestAsync : TestCase
	{
		protected override IList Mappings
		{
			get { return new string[] { "ListIndex.SimpleOneToMany.hbm.xml" }; }
		}

		protected override string MappingsAssembly
		{
			get { return "NHibernate.Test"; }
		}

		[Test]
		public async Task ShouldIncludeTheListIdxInsertingAsync()
		{
			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				var galery = new Galery();
				galery.Images.Add(new Image {Path = "image01.jpg"});
				await (s.PersistAsync(galery, CancellationToken.None));
				Assert.DoesNotThrowAsync(() => tx.CommitAsync(CancellationToken.None));
			}
			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				await (s.CreateQuery("delete from Image").ExecuteUpdateAsync(CancellationToken.None));
				await (s.CreateQuery("delete from Galery").ExecuteUpdateAsync(CancellationToken.None));
				await (tx.CommitAsync(CancellationToken.None));
			}
		}
	}
}