//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NHibernate.Cfg;
using NUnit.Framework;

namespace NHibernate.Test.DynamicEntity.Interceptor
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class InterceptorDynamicEntityAsync : TestCase
	{
		protected override string MappingsAssembly
		{
			get { return "NHibernate.Test"; }
		}

		protected override IList Mappings
		{
			get { return new string[] {"DynamicEntity.Interceptor.Customer.hbm.xml"}; }
		}

		protected override void Configure(Configuration configuration)
		{
			configuration.SetInterceptor(new ProxyInterceptor());
		}

		[Test]
		public async Task ItAsync()
		{
			// Test saving these dyna-proxies
			ISession session = OpenSession();
			session.BeginTransaction();
			Company company = ProxyHelper.NewCompanyProxy();
			company.Name = "acme";
			await (session.SaveAsync(company, CancellationToken.None));
			Customer customer = ProxyHelper.NewCustomerProxy();
			customer.Name = "Steve";
			customer.Company = company;
			await (session.SaveAsync(customer, CancellationToken.None));
			await (session.Transaction.CommitAsync(CancellationToken.None));
			session.Close();

			Assert.IsNotNull(company.Id, "company id not assigned");
			Assert.IsNotNull(customer.Id, "customer id not assigned");

			// Test loading these dyna-proxies, along with flush processing
			session = OpenSession();
			session.BeginTransaction();
			customer = await (session.LoadAsync<Customer>(customer.Id, CancellationToken.None));
			Assert.IsFalse(NHibernateUtil.IsInitialized(customer), "should-be-proxy was initialized");

			customer.Name = "other";
			await (session.FlushAsync(CancellationToken.None));
			Assert.IsFalse(NHibernateUtil.IsInitialized(customer.Company), "should-be-proxy was initialized");

			await (session.RefreshAsync(customer, CancellationToken.None));
			Assert.AreEqual("other", customer.Name, "name not updated");
			Assert.AreEqual("acme", customer.Company.Name, "company association not correct");

			await (session.Transaction.CommitAsync(CancellationToken.None));
			session.Close();

			// Test detached entity re-attachment with these dyna-proxies
			customer.Name = "Steve";
			session = OpenSession();
			session.BeginTransaction();
			await (session.UpdateAsync(customer, CancellationToken.None));
			await (session.FlushAsync(CancellationToken.None));
			await (session.RefreshAsync(customer, CancellationToken.None));
			Assert.AreEqual("Steve", customer.Name, "name not updated");
			await (session.Transaction.CommitAsync(CancellationToken.None));
			session.Close();

			// Test querying
			session = OpenSession();
			session.BeginTransaction();
			int count = (await (session.CreateQuery("from Customer").ListAsync(CancellationToken.None))).Count;
			Assert.AreEqual(1, count, "querying dynamic entity");
			session.Clear();
			count = (await (session.CreateQuery("from Person").ListAsync(CancellationToken.None))).Count;
			Assert.AreEqual(1, count, "querying dynamic entity");
			await (session.Transaction.CommitAsync(CancellationToken.None));
			session.Close();

			// test deleteing
			session = OpenSession();
			session.BeginTransaction();
			await (session.DeleteAsync(company, CancellationToken.None));
			await (session.DeleteAsync(customer, CancellationToken.None));
			await (session.Transaction.CommitAsync(CancellationToken.None));
			session.Close();
		}
	}
}