//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using NHibernate.DomainModel.NHSpecific;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest
{
	using System.Threading.Tasks;
	using System.Threading;
	/// <summary>
	/// Test mappings of <c>type="Object"</c>
	/// </summary>
	/// <remarks>
	/// Moved that mapping out of ParentChildTest because MySql has a bug with writing
	/// binary types to the database.  So any TestFixture that used <see cref="NHibernateUtil.DomainModel.Parent"/>
	/// would fail.
	/// </remarks>
	[TestFixture]
	public class BasicObjectFixtureAsync : TestCase
	{
		protected override IList Mappings
		{
			get { return new string[] {"NHSpecific.BasicObject.hbm.xml"}; }
		}

		/// <summary>
		/// This is the replacement for ParentChildTest.ObjectType() and FooBarTest.ObjectType()
		/// </summary>
		[Test]
		public async Task TestCRUDAsync()
		{
			ISession s = OpenSession();

			BasicObjectRef any = new BasicObjectRef();
			any.Name = "the any";

			IBasicObjectProxy anyProxy = new BasicObjectProxy();
			anyProxy.Name = "proxied object";

			BasicObject bo = new BasicObject();
			bo.Name = "the object";
			bo.Any = any;
			bo.AnyWithProxy = anyProxy;

			await (s.SaveAsync(any, CancellationToken.None));
			await (s.SaveAsync(anyProxy, CancellationToken.None));
			await (s.SaveAsync(bo, CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			s.Close();

			s = OpenSession();
			bo = (BasicObject) await (s.LoadAsync(typeof(BasicObject), bo.Id, CancellationToken.None));


			Assert.IsNotNull(bo.AnyWithProxy, "AnyWithProxy should not be null");
			Assert.IsTrue(bo.AnyWithProxy is IBasicObjectProxy, "AnyWithProxy should have been a IBasicObjectProxy instance");
			Assert.AreEqual(anyProxy.Id, ((IBasicObjectProxy) bo.AnyWithProxy).Id);

			Assert.IsNotNull(bo.Any, "any should not be null");
			Assert.IsTrue(bo.Any is BasicObjectRef, "any should have been a BasicObjectRef instance");
			Assert.AreEqual(any.Id, ((BasicObjectRef) bo.Any).Id);

			any = (BasicObjectRef) await (s.LoadAsync(typeof(BasicObjectRef), any.Id, CancellationToken.None));
			Assert.AreSame(any, bo.Any, "any loaded and ref by BasicObject should be the same");

			await (s.DeleteAsync(bo.Any, CancellationToken.None));
			await (s.DeleteAsync(bo.AnyWithProxy, CancellationToken.None));
			await (s.DeleteAsync(bo, CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			s.Close();
		}
	}
}