//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH887
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		[Test]
		public async Task PropertyRefReferencingParentPropertyAsync()
		{
			using (ISession s = OpenSession())
			{
				Child child = new Child();
				child.UniqueKey = 10;
				await (s.SaveAsync(child, CancellationToken.None));

				Consumer consumer = new Consumer();
				consumer.Child = child;
				await (s.SaveAsync(consumer, CancellationToken.None));
				await (s.FlushAsync(CancellationToken.None));
			}

			using (ISession s = OpenSession())
			{
				await (s.DeleteAsync("from Consumer", CancellationToken.None));
				await (s.DeleteAsync("from Child", CancellationToken.None));
				await (s.FlushAsync(CancellationToken.None));
			}
		}
	}
}