//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using NHibernate.Engine;
using NHibernate.SqlCommand;
using NHibernate.SqlTypes;
using System.Threading;
using System.Threading.Tasks;

namespace NHibernate.Driver
{
	public partial class BasicResultSetsCommand: IResultSetsCommand
	{

		public virtual async Task<DbDataReader> GetReaderAsync(int? commandTimeout)
		{
			var batcher = Session.Batcher;
			SqlType[] sqlTypes = Commands.SelectMany(c => c.ParameterTypes).ToArray();
			ForEachSqlCommand((sqlLoaderCommand, offset) => sqlLoaderCommand.ResetParametersIndexesForTheCommand(offset));
			var command = batcher.PrepareQueryCommand(CommandType.Text, sqlString, sqlTypes);
			if (commandTimeout.HasValue)
			{
				command.CommandTimeout = commandTimeout.Value;
			}
			log.Info(command.CommandText);
			BindParameters(command);
			return await (BatcherDataReaderWrapper.CreateAsync(batcher, command)).ConfigureAwait(false);
		}
	}

	/// <summary>
	/// Datareader wrapper with the same life cycle of its command (through the batcher)
	/// </summary>
	public partial class BatcherDataReaderWrapper: DbDataReader
	{

		public static async Task<BatcherDataReaderWrapper> CreateAsync(IBatcher batcher, DbCommand command)
		{
			return new BatcherDataReaderWrapper(batcher, command)
			{
				reader = await (batcher.ExecuteReaderAsync(command))
.ConfigureAwait(false)			};
		}
	}
}