//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NUnit.Framework;

namespace NHibernate.Test.IdTest
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class HiLoTableGeneratorInt16FixtureAsync : IdFixtureBase
	{
		protected override string TypeName
		{
			get { return "HiLoInt16"; }
		}

		[Test]
		public async Task ReadWriteAsync()
		{
			Int16 id;
			ISession s = OpenSession();
			HiLoInt16Class b = new HiLoInt16Class();
			await (s.SaveAsync(b, CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			id = b.Id;
			s.Close();

			s = OpenSession();
			b = (HiLoInt16Class) await (s.LoadAsync(typeof(HiLoInt16Class), b.Id, CancellationToken.None));
			Assert.AreEqual(id, b.Id);
			await (s.DeleteAsync(b, CancellationToken.None));
			await (s.FlushAsync(CancellationToken.None));
			s.Close();
		}
	}
}