//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Linq;
using System.Collections;
using NHibernate.Criterion;
using NHibernate.Engine.Query;
using NHibernate.Hql;
using NHibernate.Hql.Ast.ANTLR;
using NHibernate.Util;
using NUnit.Framework;

namespace NHibernate.Test.Hql.Ast
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class HqlFixtureAsync : BaseFixture
	{
		protected HQLQueryPlan CreateQueryPlan(string hql, bool scalar)
		{
			return new QueryExpressionPlan(new StringQueryExpression(hql), scalar, new CollectionHelper.EmptyMapClass<string, IFilter>(), sessions);
		}

		protected HQLQueryPlan CreateQueryPlan(string hql)
		{
			return CreateQueryPlan(hql, false);
		}

		private static void Check(ReturnMetadata returnMetadata, bool expectingEmptyTypes, bool expectingEmptyAliases)
		{
			Assert.IsNotNull(returnMetadata, "null return metadata");
			Assert.IsNotNull(returnMetadata, "null return metadata - types");
			Assert.AreEqual(1, returnMetadata.ReturnTypes.Length, "unexpected return size");

			if (expectingEmptyTypes)
			{
				Assert.IsNull(returnMetadata.ReturnTypes[0], "non-empty types");
			}
			else
			{
				Assert.IsNotNull(returnMetadata.ReturnTypes[0], "empty types");
			}

			if (expectingEmptyAliases)
			{
				Assert.IsNull(returnMetadata.ReturnAliases, "non-empty aliases");
			}
			else
			{
				Assert.IsNotNull(returnMetadata.ReturnAliases, "empty aliases");
				Assert.IsNotNull(returnMetadata.ReturnAliases[0], "empty aliases");
			}
		}

		[Test]
		public async Task OrderByPropertiesImplicitlySpecifiedInTheSelectAsync()
		{
			// NH-2035 
			using (ISession s = OpenSession())
			{
				await (s.CreateQuery("select distinct z from Animal a join a.zoo as z order by z.name").ListAsync(CancellationToken.None));
			}
		} 

		[Test]
		public async Task CaseClauseInSelectAsync()
		{
			// NH-322
			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.SaveAsync(new Animal {BodyWeight = 12, Description = "Polliwog"}, CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}
		
			using (ISession s = OpenSession())
			{
				var l = await (s.CreateQuery("select a.id, case when a.description = 'Polliwog' then 2 else 0 end from Animal a").ListAsync(CancellationToken.None));
				var element = (IList)l[0];
				Assert.That(element[1], Is.EqualTo(2));

				// work with alias
				l = await (s.CreateQuery("select a.id, case when a.description = 'Polliwog' then 2 else 0 end as value from Animal a").ListAsync(CancellationToken.None));
				element = (IList)l[0];
				Assert.That(element[1], Is.EqualTo(2));
			}

			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.CreateQuery("delete from Animal").ExecuteUpdateAsync(CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}
		}

		[Test]
		public async Task MultipleParametersInCaseStatementAsync()
		{
			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.SaveAsync(new Animal { BodyWeight = 12, Description = "Polliwog" }, CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}

			try
			{
				using (ISession s = OpenSession())
				{
					var result = await (s.CreateQuery("select case when 'b' = ? then 2 when 'b' = ? then 1 else 0 end from Animal a")
						.SetParameter(0, "a")
						.SetParameter(1, "b")
						.SetMaxResults(1)
						.UniqueResultAsync(CancellationToken.None));
					Assert.AreEqual(1, result);
				}
			}
			finally
			{
				using (ISession s = OpenSession())
				using (s.BeginTransaction())
				{
					await (s.CreateQuery("delete from Animal").ExecuteUpdateAsync(CancellationToken.None));
					await (s.Transaction.CommitAsync(CancellationToken.None));
				}
			}
		}

		[Test]
		public async Task ParameterInCaseThenClauseAsync()
		{
			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.SaveAsync(new Animal { BodyWeight = 12, Description = "Polliwog" }, CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}

			try
			{
				using (ISession s = OpenSession())
				{
					var result = await (s.CreateQuery("select case when 2=2 then ? else 0 end from Animal a")
						.SetParameter(0, 1)
						.UniqueResultAsync(CancellationToken.None));
					Assert.AreEqual(1, result);
				}
			}
			finally
			{
				using (ISession s = OpenSession())
				using (s.BeginTransaction())
				{
					await (s.CreateQuery("delete from Animal").ExecuteUpdateAsync(CancellationToken.None));
					await (s.Transaction.CommitAsync(CancellationToken.None));
				}
			}
		}

		[Test]
		public async Task ParameterInCaseThenAndElseClausesWithCastAsync()
		{
			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.SaveAsync(new Animal { BodyWeight = 12, Description = "Polliwog" }, CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}

			try
			{
				using (ISession s = OpenSession())
				{
					var result = await (s.CreateQuery("select case when 2=2 then cast(? as integer) else ? end from Animal a")
						.SetParameter(0, 1)
						.SetParameter(1, 0)
						.UniqueResultAsync(CancellationToken.None));
					Assert.AreEqual(1, result);
				}
			}
			finally
			{
				using (ISession s = OpenSession())
				using (s.BeginTransaction())
				{
					await (s.CreateQuery("delete from Animal").ExecuteUpdateAsync(CancellationToken.None));
					await (s.Transaction.CommitAsync(CancellationToken.None));
				}
			}
		}

		[Test]
		public async Task SubselectAdditionAsync()
		{
			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.SaveAsync(new Animal { BodyWeight = 12, Description = "Polliwog" }, CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}

			try
			{
				using (ISession s = OpenSession())
				{
					var result = await (s.CreateQuery("select count(a) from Animal a where (select count(a2) from Animal a2) + 1 > 1")
						.UniqueResultAsync(CancellationToken.None));
					Assert.AreEqual(1, result);
				}
			}
			finally
			{
				using (ISession s = OpenSession())
				using (s.BeginTransaction())
				{
					await (s.CreateQuery("delete from Animal").ExecuteUpdateAsync(CancellationToken.None));
					await (s.Transaction.CommitAsync(CancellationToken.None));
				}
			}
		}

		[Test, Ignore("Not fixed yet.")]
		public async Task SumShouldReturnDoubleAsync()
		{
			// NH-1734
			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.SaveAsync(new Human{ IntValue = 11, BodyWeight = 12.5f, Description = "Polliwog" }, CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}

			using (ISession s = OpenSession())
			{
				var l = await (s.CreateQuery("select sum(a.intValue * a.bodyWeight) from Animal a group by a.id").ListAsync(CancellationToken.None));
				Assert.That(l[0], Is.InstanceOf<Double>());
			}

			using (ISession s = OpenSession())
			using (s.BeginTransaction())
			{
				await (s.CreateQuery("delete from Animal").ExecuteUpdateAsync(CancellationToken.None));
				await (s.Transaction.CommitAsync(CancellationToken.None));
			}
		}

		[Test]
		public async Task CanParseMaxLongAsync()
		{
			// NH-1833
			using (ISession s = OpenSession())
			{
				await (s.CreateQuery(string.Format("from SimpleClass sc where sc.LongValue = {0}", long.MaxValue)).ListAsync(CancellationToken.None));
				await (s.CreateQuery(string.Format("from SimpleClass sc where sc.LongValue = {0}L", long.MaxValue)).ListAsync(CancellationToken.None));
				await (s.CreateQuery(string.Format("from SimpleClass sc where sc.LongValue = 123L")).ListAsync(CancellationToken.None));
				await (s.CreateQuery(string.Format("from SimpleClass sc where sc.LongValue = 123")).ListAsync(CancellationToken.None));
				await (s.CreateQuery(string.Format("from SimpleClass sc where sc.LongValue = {0}", int.MaxValue + 1L)).ListAsync(CancellationToken.None));
			}
		}

		[Test]
		public void InvalidJoinOnPropertyAsync()
		{
			// NH-1915
			using (ISession s = OpenSession())
			{
				Assert.ThrowsAsync<InvalidPathException>(
					() =>
					{
						return s.CreateQuery("from Zoo z inner join fetch z.classification").ListAsync(CancellationToken.None);
					},
					"Incorrect path not caught during parsing");
			}
		}

		[Test]
		public async Task InsertIntoFromSelect_WithSelectClauseParametersAsync()
		{
			using (ISession s = OpenSession())
			{
				using (s.BeginTransaction())
				{
					// arrange
					await (s.SaveAsync(new Animal() {Description = "cat1", BodyWeight = 2.1f}, CancellationToken.None));
					await (s.SaveAsync(new Animal() {Description = "cat2", BodyWeight = 2.5f}, CancellationToken.None));
					await (s.SaveAsync(new Animal() {Description = "cat3", BodyWeight = 2.7f}, CancellationToken.None));

					// act
					await (s.CreateQuery("insert into Animal (description, bodyWeight) select a.description, :weight from Animal a where a.bodyWeight < :weight")
						.SetParameter<float>("weight", 5.7f).ExecuteUpdateAsync(CancellationToken.None));

					// assert
					Assert.AreEqual(3, await (s.CreateCriteria<Animal>().SetProjection(Projections.RowCount())
					                    .Add(Restrictions.Gt("bodyWeight", 5.5f)).UniqueResultAsync<int>(CancellationToken.None)));

					await (s.CreateQuery("delete from Animal").ExecuteUpdateAsync(CancellationToken.None));
					await (s.Transaction.CommitAsync(CancellationToken.None));
				}
			}
		}


		[Test]
		public async Task UnaryMinusBeforeParenthesesHandledCorrectlyAsync()
		{
			using (ISession s = OpenSession())
			using (ITransaction txn = s.BeginTransaction())
			{
				await (s.SaveAsync(new Animal {Description = "cat1", BodyWeight = 1}, CancellationToken.None));

				// NH-2290: Unary minus before parentheses wasn't handled correctly (this query returned 0).
				int actual = (await (s.CreateQuery("select -(1+1) from Animal as h")
					.ListAsync<int>(CancellationToken.None))).Single();
				Assert.That(actual, Is.EqualTo(-2));

				// This was the workaround, which of course should still work.
				int actualWorkaround = (await (s.CreateQuery("select -1*(1+1) from Animal as h")
					.ListAsync<int>(CancellationToken.None))).Single();
				Assert.That(actualWorkaround, Is.EqualTo(-2));
			}
		}
	}
}