//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH662
{
	using System.Threading.Tasks;
	[TestFixture, Ignore("Not supported.")]
	public class FixtureAsync: BugTestCase
	{
		[Test]
		public async Task UseDerivedClassAsync()
		{
			object savedId;
			var d = new Derived {Description = "something"};

			using (ISession s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				savedId = await (s.SaveAsync(d));
				await (tx.CommitAsync());
			}

			using (ISession s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				d = await (s.LoadAsync<Derived>(savedId));
				Assert.That(d.Description, Is.EqualTo("something"));
				await (tx.CommitAsync());
			}

			using (ISession s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				await (s.DeleteAsync(d));
				await (tx.CommitAsync());
			}
		}
	}
}