//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH555
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		[Test]
		public async Task BugAsync()
		{
			using (ISession s = OpenSession())
			{
				Customer c = new Customer();
				c.Name = "TestCustomer";
				await (s.SaveAsync(c, CancellationToken.None));

				Article art = new Article();
				art.Name = "TheArticle1";
				art.Price = 10.5M;

				await (s.SaveAsync(art, CancellationToken.None));

				Order o = c.CreateNewOrder();

				OrderLine ol = o.CreateNewOrderLine();
				ol.SetArticle(art);
				ol.NumberOfItems = 5;

				o.AddOrderLine(ol);

				await (s.SaveAsync(o, CancellationToken.None));
				await (s.FlushAsync(CancellationToken.None));
			}

			using (ISession s = OpenSession())
			{
				string hql = "select sum (ol.ArticlePrice * ol.NumberOfItems) " +
				             "from Order o, OrderLine ol, Customer c " +
				             "where c.Id = :custId and o.OrderDate >= :orderDate";

				IQuery q = s.CreateQuery(hql);
				q.SetInt32("custId", 1);
				q.SetDateTime("orderDate", DateTime.Now.AddMonths(-3));

				Assert.AreEqual(52.5m, (decimal) await (q.UniqueResultAsync(CancellationToken.None)));
			}

			using (ISession s = OpenSession())
			{
				Order o = (Order) await (s.CreateQuery("from Order").UniqueResultAsync(CancellationToken.None));
				OrderLine ol = (OrderLine) o.OrderLines[0];
				await (s.DeleteAsync(ol, CancellationToken.None));
				o.OrderLines.RemoveAt(0);
				await (s.DeleteAsync(o, CancellationToken.None));
				await (s.DeleteAsync(o.OwningCustomer, CancellationToken.None));
				await (s.DeleteAsync("from Article", CancellationToken.None));
				await (s.FlushAsync(CancellationToken.None));
			}
		}
	}
}